name: unittest-poetry
on:
  push:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'discvar/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: pipx-install
      run: sudo apt update && sudo apt install pipx && pipx ensurepath
    - name: poetry-install
      run: pipx install poetry==$(cat .poetry-version)
    - name: pompon-dev-install
      run: poetry install --with test
    - name: pytest
      continue-on-error: true
      id: pytest
      run: poetry run pytest
    - name: pytest rerun failed
      if: ${{ steps.pytest.outcome == 'failure'}}
      run: poetry run pytest --lf --showlocals --tb=long --log-level=DEBUG
